using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Skylight
{
    public class Block
    {
        public int x, y, layer, id, direction;
        public Player placer;
        public World world;

        public const int LEFT_ARROW = 1;
        public const int UP_ARROW = 2;
        public const int RIGHT_ARROW = 3;
        public const int GRAVITY_DOT = 4;
        public const int CROWN = 5;
        public const int RED_KEY = 6;
        public const int GREEN_KEY = 7;
        public const int BLUE_KEY = 8;
        public const int SOLID_BASIC = 9;
        public const int SOLID_BLUE = 10;
        public const int SOLID_PURPLE = 11;
        public const int SOLID_RED = 12;
        public const int SOLID_YELLOW = 13;
        public const int SOLID_GREEN = 14;
        public const int SOLID_CYAN = 15;
        public const int BRICK_BROWN = 16;
        public const int BRICK_AQUAMARINE = 17;
        public const int BRICK_PURPLE = 18;
        public const int BRICK_GREEN = 19;
        public const int BRICK_RED = 20;
        public const int BRICK_BROWN_YELLOW = 21;
        public const int STRIPED_CONSTRUCTION = 22;
        public const int KEY_BLOCK_RED = 23;
        public const int KEY_BLOCK_GREEN = 24;
        public const int KEY_BLOCK_BLUE = 25;
        public const int KEY_BLOCK_RED_OPEN = 26;
        public const int KEY_BLOCK_GREEN_OPEN = 27;
        public const int KEY_BLOCK_BLUE_OPEN = 28;
        public const int METAL_GRAY = 29;
        public const int METAL_RED = 30;
        public const int METAL_ORANGE = 31;
        public const int FACE = 32;
        public const int GLOSSED_BLACK = 33;
        public const int GRASS_LEFT = 34;
        public const int GRASS_CENTER = 35;
        public const int GRASS_RIGHT = 36;
        public const int BETA_PURPLE = 37;
        public const int BETA_GREEN = 38;
        public const int BETA_BLUE = 39;
        public const int BETA_RED = 40;
        public const int BETA_YELLOW = 41;
        public const int BETA_GRAY = 42;
        public const int COIN_DOOR = 43;
        public const int FULLY_BLACK = 44;
        public const int CONSTRUCTION_METAL = 45;
        public const int CONSTRUCTION_GRAY = 46;
        public const int CONSTRUCTION_WOOD = 47;
        public const int CONSTRUCTION_CRATE = 48;
        public const int CONSTRUCTION_SCALE = 49;
        public const int SECRET_SOLID = 50;
        public const int GLASS_RED = 51;
        public const int GLASS_PINK = 52;
        public const int GLASS_PURPLE = 53;
        public const int GLASS_BLUE = 54;
        public const int GLASS_LIGHT_BLUE = 55;
        public const int GLASS_GREEN = 56;
        public const int GLASS_ORANGE_YELLOW = 57;
        public const int GLASS_ORANGE = 58;
        public const int SAND = 59;
        public const int CANDY_PINK = 60;
        public const int CANDY_ONE_WAY_PINK = 61;
        public const int CANDY_ONE_WAY_RED = 62;
        public const int CANDY_ONE_WAY_CYAN = 63;
        public const int CANDY_ONE_WAY_GREEN = 64;
        public const int CANDY_PEPPERMINT = 65;
        public const int CANDY_CANDY_CORN = 66;
        public const int CANDY_GINGERBREAD = 67;
        public const int HALLOWEEN_BLOOD = 68;
        public const int HALLOWEEN_BRICK = 69;
        public const int MINERAL_RED = 70;
        public const int MINERAL_PINK = 71;
        public const int MINERAL_BLUE = 72;
        public const int MINERAL_CYAN = 73;
        public const int MINERAL_GREEN = 74;
        public const int MINERAL_YELLOW = 75;
        public const int MINERAL_ORANGE = 76;
        public const int MUSIC_PIANO = 77;
        public const int XMAS_YELLOW_GREEN = 78;
        public const int XMAS_WHITE_RED = 79;
        public const int XMAS_RED_YELLOW = 80;
        public const int XMAS_BLUE_RED = 81;
        public const int XMAS_GREEN_RED = 82;
        public const int MUSIC_DRUM = 83;
        public const int SCIFI_RED = 84;
        public const int SCIFI_BLUE = 85;
        public const int SCIFI_GRAY = 86;
        public const int SCIFI_WHITE = 87;
        public const int SCIFI_BROWN = 88;
        public const int SCIFI_ONE_WAY_RED = 89;
        public const int SCIFI_ONE_WAY_BLUE = 90;
        public const int SCIFI_ONE_WAY_GREEN = 91;
        public const int JAIL_BRICK = 92;
        public const int PIRATE_PLANK = 93;
        public const int PIRATE_CHEST = 94;
        public const int VIKING_BRICK = 95;
        //96-97: Unknown/Reserved
        public const int INVISIBLE_SOLID_1 = 98;
        public const int INVISIBLE_SOLID_2 = 99;
        public const int COIN_GOLD = 100;
        public const int COIN_BLUE = 101;
        //102-109: Unknown/Reserved
        public const int COIN_GOLD_COLLECTED = 110;
        public const int COIN_BLUE_COLLECTED = 111;
        //112-217: Unknown/Reserved
        //Decorations:
        public const int XMAS_ORNAMENT_RED = 218;
        public const int XMAS_ORNAMENT_GREEN = 219;
        public const int XMAS_ORNAMENT_BLUE = 220;
        public const int XMAS_WREATH = 221;
        public const int XMAS_STAR = 222;
        //223: Unknown/Reserved
        public const int HALLOWEEN_GRAVESTONE = 224;
        public const int HALLOWEEN_WEB_LEFT = 225;
        public const int HALLOWEEN_WEB_RIGHT = 226;
        public const int CANDY_PUFF = 227;
        public const int SUMMER_UMBRELLA = 228;
        public const int SUMMER_SAND_RIGHT = 229;
        public const int SUMMER_SAND_LEFT = 230;
        public const int SUMMER_ROCK = 231;
        public const int SUMMER_SHRUB = 232;
        public const int SPRING_GRASS_LEFT = 233;
        public const int SPRING_GRASS_MIDDLE = 234;
        public const int SPRING_GRASS_RIGHT = 235;
        public const int SPRING_HEDGE_LEFT = 236;
        public const int SPRING_HEDGE_MIDDLE = 237;
        public const int SPRING_HEDGE_RIGHT = 238;
        public const int SPRING_FLOWER = 239;
        public const int SPRING_SHRUB = 240;
        //241-242: Unknown/Reserved
        public const int SECRET_FULLY_BLACK = 243;
        public const int NEWYEAR_PURPLE = 244;
        public const int NEWYEAR_GOLD = 245;
        public const int NEWYEAR_BLUE = 246;
        public const int NEWYEAR_RED = 247;
        public const int NEWYEAR_GREEN = 248;
        public const int XMAS_SNOW_RIGHT = 249;
        public const int XMAS_SNOW_LEFT = 250;
        public const int XMAS_TREE = 251;
        public const int XMAS_TREE_LIT = 252;
        public const int XMAS_FENCE_SNOW = 253;
        public const int XMAS_FENCE = 254;
        public const int SPAWN_POINT = 255;
        public const int EASTER_EGG_BLUE = 256;
        public const int EASTER_EGG_PURPLE = 257;
        public const int EASTER_EGG_YELLOW = 258;
        public const int EASTER_EGG_RED = 259;
        public const int EASTER_EGG_GREEN = 260;
        public const int JAIL_BARS = 261;
        public const int DECOR_GLASS_CLEAR = 262;
        public const int DECOR_GLASS_GREEN = 263;
        public const int DECOR_GLASS_CYAN = 264;
        public const int DECOR_GLASS_BLUE = 265;
        public const int DECOR_GLASS_PURPLE = 266;
        public const int DECOR_GLASS_RED = 267;
        public const int DECOR_GLASS_ORANGE = 268;
        public const int DECOR_GLASS_YELLOW = 269;
        public const int PIRATE_GONG = 270;
        public const int PIRATE_SKULL = 271;
        public const int VIKING_SHIELD_RED = 272;
        public const int VIKING_SHIELD_BLUE = 273;
        public const int VIKING_AXE = 274;
        //275-499: Unknown/Reserved
    }
}
