using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Skylight
{
    public class Block
    {
        public int x { get; internal set; }
        public int y { get; internal set; }
        public int layer { get; internal set; }
        public int id { get; internal set; }
        public int direction { get; internal set; }
        public Player placer { get; internal set; }
        public World world { get; internal set; }

        public readonly int LEFT_ARROW = 1;
        public readonly int UP_ARROW = 2;
        public readonly int RIGHT_ARROW = 3;
        public readonly int GRAVITY_DOT = 4;
        public readonly int CROWN = 5;
        public readonly int RED_KEY = 6;
        public readonly int GREEN_KEY = 7;
        public readonly int BLUE_KEY = 8;
        public readonly int SOLID_BASIC = 9;
        public readonly int SOLID_BLUE = 10;
        public readonly int SOLID_PURPLE = 11;
        public readonly int SOLID_RED = 12;
        public readonly int SOLID_YELLOW = 13;
        public readonly int SOLID_GREEN = 14;
        public readonly int SOLID_CYAN = 15;
        public readonly int BRICK_BROWN = 16;
        public readonly int BRICK_AQUAMARINE = 17;
        public readonly int BRICK_PURPLE = 18;
        public readonly int BRICK_GREEN = 19;
        public readonly int BRICK_RED = 20;
        public readonly int BRICK_BROWN_YELLOW = 21;
        public readonly int STRIPED_CONSTRUCTION = 22;
        public readonly int KEY__RED = 23;
        public readonly int KEY__GREEN = 24;
        public readonly int KEY__BLUE = 25;
        public readonly int KEY__RED_OPEN = 26;
        public readonly int KEY__GREEN_OPEN = 27;
        public readonly int KEY__BLUE_OPEN = 28;
        public readonly int METAL_GRAY = 29;
        public readonly int METAL_RED = 30;
        public readonly int METAL_ORANGE = 31;
        public readonly int FACE = 32;
        public readonly int GLOSSED_BLACK = 33;
        public readonly int GRASS_LEFT = 34;
        public readonly int GRASS_CENTER = 35;
        public readonly int GRASS_RIGHT = 36;
        public readonly int BETA_PURPLE = 37;
        public readonly int BETA_GREEN = 38;
        public readonly int BETA_BLUE = 39;
        public readonly int BETA_RED = 40;
        public readonly int BETA_YELLOW = 41;
        public readonly int BETA_GRAY = 42;
        public readonly int COIN_DOOR = 43;
        public readonly int FULLY_BLACK = 44;
        public readonly int CONSTRUCTION_METAL = 45;
        public readonly int CONSTRUCTION_GRAY = 46;
        public readonly int CONSTRUCTION_WOOD = 47;
        public readonly int CONSTRUCTION_CRATE = 48;
        public readonly int CONSTRUCTION_SCALE = 49;
        public readonly int SECRET_SOLID = 50;
        public readonly int GLASS_RED = 51;
        public readonly int GLASS_PINK = 52;
        public readonly int GLASS_PURPLE = 53;
        public readonly int GLASS_BLUE = 54;
        public readonly int GLASS_LIGHT_BLUE = 55;
        public readonly int GLASS_GREEN = 56;
        public readonly int GLASS_ORANGE_YELLOW = 57;
        public readonly int GLASS_ORANGE = 58;
        public readonly int SAND = 59;
        public readonly int CANDY_PINK = 60;
        public readonly int CANDY_ONE_WAY_PINK = 61;
        public readonly int CANDY_ONE_WAY_RED = 62;
        public readonly int CANDY_ONE_WAY_CYAN = 63;
        public readonly int CANDY_ONE_WAY_GREEN = 64;
        public readonly int CANDY_PEPPERMINT = 65;
        public readonly int CANDY_CANDY_CORN = 66;
        public readonly int CANDY_GINGERBREAD = 67;
        public readonly int HALLOWEEN_BLOOD = 68;
        public readonly int HALLOWEEN_BRICK = 69;
        public readonly int MINERAL_RED = 70;
        public readonly int MINERAL_PINK = 71;
        public readonly int MINERAL_BLUE = 72;
        public readonly int MINERAL_CYAN = 73;
        public readonly int MINERAL_GREEN = 74;
        public readonly int MINERAL_YELLOW = 75;
        public readonly int MINERAL_ORANGE = 76;
        public readonly int MUSIC_PIANO = 77;
        public readonly int XMAS_YELLOW_GREEN = 78;
        public readonly int XMAS_WHITE_RED = 79;
        public readonly int XMAS_RED_YELLOW = 80;
        public readonly int XMAS_BLUE_RED = 81;
        public readonly int XMAS_GREEN_RED = 82;
        public readonly int MUSIC_DRUM = 83;
        public readonly int SCIFI_RED = 84;
        public readonly int SCIFI_BLUE = 85;
        public readonly int SCIFI_GRAY = 86;
        public readonly int SCIFI_WHITE = 87;
        public readonly int SCIFI_BROWN = 88;
        public readonly int SCIFI_ONE_WAY_RED = 89;
        public readonly int SCIFI_ONE_WAY_BLUE = 90;
        public readonly int SCIFI_ONE_WAY_GREEN = 91;
        public readonly int JAIL_BRICK = 92;
        public readonly int PIRATE_PLANK = 93;
        public readonly int PIRATE_CHEST = 94;
        public readonly int VIKING_BRICK = 95;
        //96-97: Unknown/Reserved
        public readonly int INVISIBLE_SOLID_1 = 98;
        public readonly int INVISIBLE_SOLID_2 = 99;
        public readonly int COIN_GOLD = 100;
        public readonly int COIN_BLUE = 101;
        //102-109: Unknown/Reserved
        public readonly int COIN_GOLD_COLLECTED = 110;
        public readonly int COIN_BLUE_COLLECTED = 111;
        //112-217: Unknown/Reserved
        //Decorations:
        public readonly int XMAS_ORNAMENT_RED = 218;
        public readonly int XMAS_ORNAMENT_GREEN = 219;
        public readonly int XMAS_ORNAMENT_BLUE = 220;
        public readonly int XMAS_WREATH = 221;
        public readonly int XMAS_STAR = 222;
        //223: Unknown/Reserved
        public readonly int HALLOWEEN_GRAVESTONE = 224;
        public readonly int HALLOWEEN_WEB_LEFT = 225;
        public readonly int HALLOWEEN_WEB_RIGHT = 226;
        public readonly int CANDY_PUFF = 227;
        public readonly int SUMMER_UMBRELLA = 228;
        public readonly int SUMMER_SAND_RIGHT = 229;
        public readonly int SUMMER_SAND_LEFT = 230;
        public readonly int SUMMER_ROCK = 231;
        public readonly int SUMMER_SHRUB = 232;
        public readonly int SPRING_GRASS_LEFT = 233;
        public readonly int SPRING_GRASS_MIDDLE = 234;
        public readonly int SPRING_GRASS_RIGHT = 235;
        public readonly int SPRING_HEDGE_LEFT = 236;
        public readonly int SPRING_HEDGE_MIDDLE = 237;
        public readonly int SPRING_HEDGE_RIGHT = 238;
        public readonly int SPRING_FLOWER = 239;
        public readonly int SPRING_SHRUB = 240;
        //241-242: Unknown/Reserved
        public readonly int SECRET_FULLY_BLACK = 243;
        public readonly int NEWYEAR_PURPLE = 244;
        public readonly int NEWYEAR_GOLD = 245;
        public readonly int NEWYEAR_BLUE = 246;
        public readonly int NEWYEAR_RED = 247;
        public readonly int NEWYEAR_GREEN = 248;
        public readonly int XMAS_SNOW_RIGHT = 249;
        public readonly int XMAS_SNOW_LEFT = 250;
        public readonly int XMAS_TREE = 251;
        public readonly int XMAS_TREE_LIT = 252;
        public readonly int XMAS_FENCE_SNOW = 253;
        public readonly int XMAS_FENCE = 254;
        public readonly int SPAWN_POINT = 255;
        public readonly int EASTER_EGG_BLUE = 256;
        public readonly int EASTER_EGG_PURPLE = 257;
        public readonly int EASTER_EGG_YELLOW = 258;
        public readonly int EASTER_EGG_RED = 259;
        public readonly int EASTER_EGG_GREEN = 260;
        public readonly int JAIL_BARS = 261;
        public readonly int DECOR_GLASS_CLEAR = 262;
        public readonly int DECOR_GLASS_GREEN = 263;
        public readonly int DECOR_GLASS_CYAN = 264;
        public readonly int DECOR_GLASS_BLUE = 265;
        public readonly int DECOR_GLASS_PURPLE = 266;
        public readonly int DECOR_GLASS_RED = 267;
        public readonly int DECOR_GLASS_ORANGE = 268;
        public readonly int DECOR_GLASS_YELLOW = 269;
        public readonly int PIRATE_GONG = 270;
        public readonly int PIRATE_SKULL = 271;
        public readonly int VIKING_SHIELD_RED = 272;
        public readonly int VIKING_SHIELD_BLUE = 273;
        public readonly int VIKING_AXE = 274;
        //275-499: Unknown/Reserved
        public readonly int BG_BASIC_GRAY = 500;
        public readonly int BG_BASIC_BLUE = 501;
        public readonly int BG_BASIC_PURPLE = 502;
        public readonly int BG_BASIC_RED = 503;
        public readonly int BG_BASIC_YELLOW = 504;
        public readonly int BG_BASIC_GREEN = 505;
        public readonly int BG_BASIC_CYAN = 506;
        public readonly int BG_BRICK_BROWN = 507;
        public readonly int BG_BRICK_TEAL = 508;
        public readonly int BG_BRICK_PURPLE = 509;
        public readonly int BG_BRICK_GREEN = 510;
        public readonly int BG_BRICK_RED = 511;
        public readonly int BG_BRICK_TAN = 512;
        public readonly int BG_CHECKER_GRAY = 513;
        public readonly int BG_CHECKER_BLUE = 514;
        public readonly int BG_CHECKER_PURPLE = 515;
        public readonly int BG_CHECKER_RED = 516;
        public readonly int BG_CHECKER_YELLOW = 517;
        public readonly int BG_CHECKER_GREEN = 518;
        public readonly int BG_CHECKER_CYAN = 519;
        public readonly int BG_DARK_GRAY = 520;
        public readonly int BG_DARK_BLUE = 521;
        public readonly int BG_DARK_PURPLE = 522;
        public readonly int BG_DARK_RED = 523;
        public readonly int BG_DARK_YELLOW = 524;
        public readonly int BG_DARK_GREEN = 525;
        public readonly int BG_DARK_CYAN = 526;
        public readonly int BG_PASTEL_ORANGE = 527;
        public readonly int BG_PASTEL_GREEN = 528;
        public readonly int BG_PASTEL_YELLOW = 529;
        public readonly int BG_PASTEL_TEAL = 530;
        public readonly int BG_PASTEL_BLUE = 531;
        public readonly int BG_PASTEL_RED = 532;
        public readonly int BG_CANVAS_RED = 533;
        public readonly int BG_CANVAS_TAN = 534;
        public readonly int BG_CANVAS_ORANGE = 535;
        public readonly int BG_CANVAS_GREEN = 536;
        public readonly int BG_CANVAS_BLUE = 537;
        public readonly int BG_CANVAS_GRAY = 538;
        public readonly int BG_CANDY_PINK = 539;
        public readonly int BG_CANDY_BLUE = 540;
        public readonly int BG_HALLOWEEN_GRAY = 541;
        public readonly int BG_HALLOWEEN_BRICK = 542;
        public readonly int BG_HALLOWEEN_STAIR_LEFT = 543;
        public readonly int BG_HALLOWEEN_STAIR_RIGHT = 544;
        public readonly int BG_CARNIVAL_STRIPE_RED = 545;
        public readonly int BG_CARNIVAL_STRIPE_PURPLE = 546;
        public readonly int BG_CARNIVAL_PINK = 547;
        public readonly int BG_CARNIVAL_CHECKER = 548;
        public readonly int BG_CARNIVAL_GREEN = 549;
        public readonly int BG_JAIL_BRICK = 550;
        public readonly int BG_JAIL_WINDOW = 551;
        public readonly int BG_JAIL_BARS = 552;
        public readonly int BG_JAIL_BARS_DARK = 553;
        public readonly int BG_PIRATE_PLANK_DARK = 554;
        public readonly int BG_PIRATE_PLANK_LIGHT = 555;
        public readonly int BG_PIRATE_PLANK_PEGS = 556;
        public readonly int BG_PIRATE_LIFE_SAVER = 557;
        public readonly int BG_PIRATE_WINDOW = 558;
        public readonly int BG_PIRATE_CANNON = 559;
        public readonly int BG_PIRATE_SKULL = 560;
        public readonly int BG_VIKING_BRICK = 561;
        public readonly int BG_VIKING_BRICK2 = 562;
        public readonly int BG_VIKING_STRIPE = 563;
        // 564+: Unknown/Reserved
    }
}
